config/routes.rb
Rails.application.routes.draw do
  resources :employees
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
# test


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employee.rb
class Employee < ApplicationRecord
  validates :emp_name, presence: true
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(employee_params)

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(employee_params)
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee.destroy
    respond_to do |format|
      format.html { redirect_to employees_url, notice: 'Employee was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_employee
      @employee = Employee.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def employee_params
      params.require(:employee).permit(:emp_name, :emp_age, :emp_sex, :emp_design, :emp_salary, :emp_phone, :emp_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/views/employees/_form.html.erb
<%= form_with(model: employee, local: true) do |form| %>
  <% if employee.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
      <% employee.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :emp_name %>
    <%= form.text_area :emp_name, id: :employee_emp_name %>
  </div>

  <div class="field">
    <%= form.label :emp_age %>
    <%= form.text_field :emp_age, id: :employee_emp_age %>
  </div>

  <div class="field">
    <%= form.label :emp_sex %>
    <%= form.text_field :emp_sex, id: :employee_emp_sex %>
  </div>

  <div class="field">
    <%= form.label :emp_design %>
    <%= form.text_area :emp_design, id: :employee_emp_design %>
  </div>

  <div class="field">
    <%= form.label :emp_salary %>
    <%= form.text_field :emp_salary, id: :employee_emp_salary %>
  </div>

  <div class="field">
    <%= form.label :emp_phone %>
    <%= form.text_field :emp_phone, id: :employee_emp_phone %>
  </div>

  <div class="field">
    <%= form.label :emp_email %>
    <%= form.text_area :emp_email, id: :employee_emp_email %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

app/views/employees/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Employees</h1>

<table>
  <thead>
    <tr>
      <th>Emp name</th>
      <th>Emp age</th>
      <th>Emp sex</th>
      <th>Emp design</th>
      <th>Emp salary</th>
      <th>Emp phone</th>
      <th>Emp email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @employees.each do |employee| %>
      <tr>
        <td><%= employee.emp_name %></td>
        <td><%= employee.emp_age %></td>
        <td><%= employee.emp_sex %></td>
        <td><%= employee.emp_design %></td>
        <td><%= employee.emp_salary %></td>
        <td><%= employee.emp_phone %></td>
        <td><%= employee.emp_email %></td>
        <td><%= link_to 'Show', employee %></td>
        <td><%= link_to 'Edit', edit_employee_path(employee) %></td>
        <td><%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Employee', new_employee_path %>

app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Emp name:</strong>
  <%= @employee.emp_name %>
</p>

<p>
  <strong>Emp age:</strong>
  <%= @employee.emp_age %>
</p>

<p>
  <strong>Emp sex:</strong>
  <%= @employee.emp_sex %>
</p>

<p>
  <strong>Emp design:</strong>
  <%= @employee.emp_design %>
</p>

<p>
  <strong>Emp salary:</strong>
  <%= @employee.emp_salary %>
</p>

<p>
  <strong>Emp phone:</strong>
  <%= @employee.emp_phone %>
</p>

<p>
  <strong>Emp email:</strong>
  <%= @employee.emp_email %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Employeeapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>